theme: jekyll-theme-dinky
title: CSRG
logo: img/csrg.jpg
description: Concurrent Sysyems Research Group<br />University of Sydney<br />1, Cleveland St., <br /> NSW 2006 Sydney<br /><a href="mailto:csrg.sydney@gmail.com">csrg.sydney@gmail.com</a><br />
show_downloads: "false"
