theme: jekyll-theme-dinky
title: CSRG
logo: img/csrg.png
description: School of Computer Science <br /> 1, Cleveland St., <br /> NSW 2006 Sydney<br /><a href="mailto:csrg.sydney@gmail.com">csrg.sydney@gmail.com</a><br />
